// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlc0uxFM-OF_3USqDbn9Dz8BTd2QS25jM',
    appId: '1:1023944304750:web:e08cffd7c05d4ab6a15e7f',
    messagingSenderId: '1023944304750',
    projectId: 'pandalist-f53bc',
    authDomain: 'pandalist-f53bc.firebaseapp.com',
    storageBucket: 'pandalist-f53bc.firebasestorage.app',
    measurementId: 'G-5J86TKSVJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAwfzVu6YFEfLy7PAVhE9VyF0hbKT3Gkw',
    appId: '1:1023944304750:android:65fb5efe04294603a15e7f',
    messagingSenderId: '1023944304750',
    projectId: 'pandalist-f53bc',
    storageBucket: 'pandalist-f53bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLDwr2c61qNjSA2VcWu2Xn2qvCzGTxGo',
    appId: '1:1023944304750:ios:e17df3963aed9cb2a15e7f',
    messagingSenderId: '1023944304750',
    projectId: 'pandalist-f53bc',
    storageBucket: 'pandalist-f53bc.firebasestorage.app',
    iosClientId: '1023944304750-tr82dc59fiqkiepg66q7ri6gconfja05.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
